spring:
  application:
    name: spring-cloud-consume-demo

server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1.com:8000/eureka/,http://peer2.com:8001/eureka/,http://peer3.com:8002/eureka/