spring:
  application:
    name: spring-cloud-eureka01
  profiles:
    active: peer2.com
server:
  port: 8001
eureka:
  instance:
    hostname: peer2.com
  client:
    serviceUrl:
      defaultZone: http://peer1.com:8000/eureka/,http://peer3.com:8002/eureka/