spring:
  application:
    name: spring-cloud-service-demo
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1.com:8000/eureka/,http://peer2.com:8001/eureka/,http://peer3.com:8002/eureka/